/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-07-21 07:57:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/board/../includes/footer.jsp", Long.valueOf(1594104372406L));
    _jspx_dependants.put("/WEB-INF/views/board/../includes/header.jsp", Long.valueOf(1594104372411L));
    _jspx_dependants.put("jar:file:/D:/springsource/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1592371395588L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/mycss.css\" />\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <title>스프링 게시판</title>\r\n");
      out.write("    <!-- Bootstrap Core CSS -->\r\n");
      out.write("    <link href=\"/resources/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- MetisMenu CSS -->\r\n");
      out.write("   <link href=\"/resources/vendor/metisMenu/metisMenu.min.css\" rel=\"stylesheet\"> \r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"/resources/dist/css/sb-admin-2.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Custom Fonts -->\r\n");
      out.write("    <link href=\"/resources/vendor/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">   \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        <!-- Navigation -->\r\n");
      out.write("        <nav class=\"navbar navbar-default navbar-static-top\" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"/board/list\">Spring MVC/Mybatis/Oracle</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-header -->\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav navbar-top-links navbar-right\">\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("                        <i class=\"fa fa-envelope fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-messages\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <strong>John Smith</strong>\r\n");
      out.write("                                    <span class=\"pull-right text-muted\">\r\n");
      out.write("                                        <em>Yesterday</em>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <strong>John Smith</strong>\r\n");
      out.write("                                    <span class=\"pull-right text-muted\">\r\n");
      out.write("                                        <em>Yesterday</em>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <strong>John Smith</strong>\r\n");
      out.write("                                    <span class=\"pull-right text-muted\">\r\n");
      out.write("                                        <em>Yesterday</em>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"text-center\" href=\"#\">\r\n");
      out.write("                                <strong>Read All Messages</strong>\r\n");
      out.write("                                <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- /.dropdown-messages -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- /.dropdown -->\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("                        <i class=\"fa fa-tasks fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-tasks\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        <strong>Task 1</strong>\r\n");
      out.write("                                        <span class=\"pull-right text-muted\">40% Complete</span>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <div class=\"progress progress-striped active\">\r\n");
      out.write("                                        <div class=\"progress-bar progress-bar-success\" role=\"progressbar\" aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 40%\">\r\n");
      out.write("                                            <span class=\"sr-only\">40% Complete (success)</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        <strong>Task 2</strong>\r\n");
      out.write("                                        <span class=\"pull-right text-muted\">20% Complete</span>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <div class=\"progress progress-striped active\">\r\n");
      out.write("                                        <div class=\"progress-bar progress-bar-info\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 20%\">\r\n");
      out.write("                                            <span class=\"sr-only\">20% Complete</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        <strong>Task 3</strong>\r\n");
      out.write("                                        <span class=\"pull-right text-muted\">60% Complete</span>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <div class=\"progress progress-striped active\">\r\n");
      out.write("                                        <div class=\"progress-bar progress-bar-warning\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%\">\r\n");
      out.write("                                            <span class=\"sr-only\">60% Complete (warning)</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        <strong>Task 4</strong>\r\n");
      out.write("                                        <span class=\"pull-right text-muted\">80% Complete</span>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <div class=\"progress progress-striped active\">\r\n");
      out.write("                                        <div class=\"progress-bar progress-bar-danger\" role=\"progressbar\" aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 80%\">\r\n");
      out.write("                                            <span class=\"sr-only\">80% Complete (danger)</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"text-center\" href=\"#\">\r\n");
      out.write("                                <strong>See All Tasks</strong>\r\n");
      out.write("                                <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- /.dropdown-tasks -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- /.dropdown -->\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("                        <i class=\"fa fa-bell fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-alerts\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <i class=\"fa fa-comment fa-fw\"></i> New Comment\r\n");
      out.write("                                    <span class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <i class=\"fa fa-twitter fa-fw\"></i> 3 New Followers\r\n");
      out.write("                                    <span class=\"pull-right text-muted small\">12 minutes ago</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <i class=\"fa fa-envelope fa-fw\"></i> Message Sent\r\n");
      out.write("                                    <span class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <i class=\"fa fa-tasks fa-fw\"></i> New Task\r\n");
      out.write("                                    <span class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <i class=\"fa fa-upload fa-fw\"></i> Server Rebooted\r\n");
      out.write("                                    <span class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"text-center\" href=\"#\">\r\n");
      out.write("                                <strong>See All Alerts</strong>\r\n");
      out.write("                                <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- /.dropdown-alerts -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- /.dropdown -->\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("                        <i class=\"fa fa-user fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-user\">\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-user fa-fw\"></i> User Profile</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-gear fa-fw\"></i> Settings</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"login.html\"><i class=\"fa fa-sign-out fa-fw\"></i> Logout</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- /.dropdown-user -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- /.dropdown -->\r\n");
      out.write("            </ul>\r\n");
      out.write("            <!-- /.navbar-top-links -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"navbar-default sidebar\" role=\"navigation\">\r\n");
      out.write("                <div class=\"sidebar-nav navbar-collapse\">\r\n");
      out.write("                    <ul class=\"nav\" id=\"side-menu\">\r\n");
      out.write("                        <li class=\"sidebar-search\">\r\n");
      out.write("                            <div class=\"input-group custom-search-form\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\r\n");
      out.write("                                <span class=\"input-group-btn\">\r\n");
      out.write("                                <button class=\"btn btn-default\" type=\"button\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /input-group -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"/board/register\"><i class=\"fa fa-dashboard fa-fw\"></i> Dashboard</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-bar-chart-o fa-fw\"></i> Charts<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Flot Charts</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Morris.js Charts</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <!-- /.nav-second-level -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-table fa-fw\"></i> Tables</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-edit fa-fw\"></i> Forms</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-wrench fa-fw\"></i> UI Elements<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Panels and Wells</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Buttons</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Notifications</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Typography</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\"> Icons</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Grid</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <!-- /.nav-second-level -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-sitemap fa-fw\"></i> Multi-Level Dropdown<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Second Level Item</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Second Level Item</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Third Level <span class=\"fa arrow\"></span></a>\r\n");
      out.write("                                    <ul class=\"nav nav-third-level\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">Third Level Item</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">Third Level Item</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">Third Level Item</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">Third Level Item</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <!-- /.nav-third-level -->\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <!-- /.nav-second-level -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-files-o fa-fw\"></i> Sample Pages<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Blank Page</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Login Page</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <!-- /.nav-second-level -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.sidebar-collapse -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-static-side -->\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div id=\"page-wrapper\">\r\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <h1 class=\"page-header\">Board Modify</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.col-lg-12 -->\r\n");
      out.write("            </div>            \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                \t<div class=\"panel panel-default\">\r\n");
      out.write("                        <div class=\"panel-heading\">\r\n");
      out.write("                           Board Modify Page\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- /.panel-heading -->\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                \t\t\t<form action=\"\" method=\"post\" role=\"form\">\r\n");
      out.write("                \t\t\t\t<div class=\"form-group\">\r\n");
      out.write("                \t\t\t\t\t<label>Bno</label>\r\n");
      out.write("                \t\t\t\t\t<input class=\"form-control\" name=\"bno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modify.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">                \t\t\t\t\r\n");
      out.write("                \t\t\t\t</div> \r\n");
      out.write("                \t\t\t\t<div class=\"form-group\">\r\n");
      out.write("                \t\t\t\t\t<label>Title</label>\r\n");
      out.write("                \t\t\t\t\t<input class=\"form-control\" name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modify.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">                \t\t\t\t\r\n");
      out.write("                \t\t\t\t</div>  \r\n");
      out.write("                \t\t\t\t<div class=\"form-group\">\r\n");
      out.write("                \t\t\t\t\t<label>Content</label>\r\n");
      out.write("                \t\t\t\t\t<textarea class=\"form-control\" rows=\"3\" name=\"content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modify.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>               \t\t\t\t\r\n");
      out.write("                \t\t\t\t</div> \r\n");
      out.write("                \t\t\t\t<div class=\"form-group\">\r\n");
      out.write("                \t\t\t\t\t<label>Writer</label>\r\n");
      out.write("                \t\t\t\t\t<input class=\"form-control\" name=\"writer\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modify.writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">                \t\t\t\t\r\n");
      out.write("                \t\t\t\t</div>\r\n");
      out.write("                \t\t\t\t<button type=\"submit\" data-oper='modify' class=\"btn btn-success\">Modify</button>              \t\t\t\r\n");
      out.write("                \t\t\t\t<button type=\"submit\" data-oper='remove' class=\"btn btn-danger\" onclick=\"location.href='/board/remove?bno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modify.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">Remove</button>                \t\t\t\t\r\n");
      out.write("                \t\t\t\t<button type=\"submit\" data-oper='list' class=\"btn btn-info\" onclick=\"location.href='/board/list'\">List</button>              \t\t\t\r\n");
      out.write("                \t\t\t</form>\r\n");
      out.write("                \t\t</div>\r\n");
      out.write("                \t</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("   \r\n");
      out.write("<div class=\"bigPictureWrapper\">\r\n");
      out.write("\t<div class=\"bigPicture\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>  \r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t<div class=\"panel-heading\"><i class=\"fa fas fa-file\"></i>Files</div>\r\n");
      out.write("\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group uploadDiv\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" name=\"uploadFile\" multiple=\"multiple\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"uploadResult\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("<form method=\"post\" id=\"myForm\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"bno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modify.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"pageNum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${criteriaVO.pageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"amount\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${criteriaVO.amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"type\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${criteriaVO.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${criteriaVO.keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function showImage(fileCallPath){\r\n");
      out.write("\t$(\".bigPictureWrapper\").css(\"display\", \"flex\").show();\t\r\n");
      out.write("\t$(\".bigPicture\").html(\"<img src='/display?fileName=\"+fileCallPath+\"'>\").animate({width: '100%', height: '100%'}, 1000);\r\n");
      out.write("}\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"input[type='file']\").change(function(){\r\n");
      out.write("\t\t//form 형태로 데이터를 구성할 수 있다\r\n");
      out.write("\t\t//key-value의 형태로 값을 찾아온다\r\n");
      out.write("\t\tlet formData = new FormData();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//첨부파일 목록 가져오기\r\n");
      out.write("\t\tlet uploadFile=$(\"input[name='uploadFile']\");\t\t\r\n");
      out.write("\t\tlet files=uploadFile[0].files;\r\n");
      out.write("\t\tconsole.log(files);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//form의 형태로 붙이기\r\n");
      out.write("\t\t//첨부파일 Type 및 Size 제한\r\n");
      out.write("\t\tfor(var i=0;i<files.length;i++){\r\n");
      out.write("\t\t\tif(!checkExtension(files[i].name, files[i].size)){\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tformData.append(\"uploadFile\", files[i]);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//processData : 데이터를 query string(http://~~?uploadFile=테스트.txt&)으로 변환할 것인지 결정 \r\n");
      out.write("\t\t//\t\t\t\t(Default : application/x-www-form-urlencoded로 true)\r\n");
      out.write("\t\t//contentType : 파일의 경우에 enctype은 multipart/form-data로 보내야 하기 때문에 false로 지정 \r\n");
      out.write("\t\t//\t\t\t\t(Default : application/x-www-form-urlencoded로 true)\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"/uploadAjax\",\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\tprocessData:false,\r\n");
      out.write("\t\t\tcontentType:false,\r\n");
      out.write("\t\t\tdata:formData,\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\tshowUploadFile(result);\r\n");
      out.write("\t\t\t\t/* alert(result); */\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(xhr, status, error){\r\n");
      out.write("\t\t\t\talert(xhr.responseText);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t//업로드 된 파일 보여주기\r\n");
      out.write("\tfunction showUploadFile(uploadResultArr){\r\n");
      out.write("\t\tlet str=\"\";\r\n");
      out.write("\t\t//결과를 보여줄 영역 가져오기\r\n");
      out.write("\t\tlet uploadResult=$(\".uploadResult ul\");\r\n");
      out.write("\t\t$(uploadResultArr).each(function(i, element){\r\n");
      out.write("\t\t\tif(element.fileType){//이미지 파일 => true\r\n");
      out.write("\t\t\t\t//썸네일 이미지 경로\r\n");
      out.write("\t\t\t\tvar fileCallPath=encodeURIComponent(element.uploadPath+\"\\\\s_\"+element.uuid+\"_\"+element.fileName);\r\n");
      out.write("\t\t\t\t//원본 이미지 경로\r\n");
      out.write("\t\t\t\tvar originalPath=element.uploadPath+\"\\\\\"+element.uuid+\"_\"+element.fileName;\r\n");
      out.write("\t\t\t\toriginalPath=originalPath.replace(new RegExp(/\\\\/g), \"/\");\r\n");
      out.write("\t\t\t\tstr+=\"<li data-path='\"+element.uploadPath+\"' data-uuid='\"+element.uuid+\"'\";\r\n");
      out.write("\t\t\t\tstr+=\" data-filename='\"+element.fileName+\"' data-type='\"+element.fileType+\"'>\";\r\n");
      out.write("\t\t\t\tstr+=\"<a href=\\\"javascript:showImage(\\'\"+originalPath+\"\\')\\\">\";\r\n");
      out.write("\t\t\t\tstr+=\"<img src='/display?fileName=\"+fileCallPath+\"'><div>\"+element.fileName+\"</a>\";\r\n");
      out.write("\t\t\t\tstr+=\"<button type='button' class='btn btn-danger btn-circle btn-sm'>\";\r\n");
      out.write("\t\t\t\tstr+=\"<i class='fa fa-times'></i></button></span></div></li>\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else{//일반 파일 => false\r\n");
      out.write("\t\t\t\tvar fileCallPath=encodeURIComponent(element.uploadPath+\"\\\\\"+element.uuid+\"_\"+element.fileName);\r\n");
      out.write("\t\t\t\tstr+=\"<li data-path='\"+element.uploadPath+\"' data-uuid='\"+element.uuid+\"'\";\r\n");
      out.write("\t\t\t\tstr+=\" data-filename='\"+element.fileName+\"' data-type='\"+element.fileType+\"'>\";\r\n");
      out.write("\t\t\t\tstr+=\"<a href='/download?fileName=\"+fileCallPath+\"'>\";\r\n");
      out.write("\t\t\t\tstr+=\"<img src='/resources/img/attach.png'><div>\"+element.fileName+\"</a>\";\r\n");
      out.write("\t\t\t\tstr+=\"<button type='button' class='btn btn-danger btn-circle btn-sm'>\";\r\n");
      out.write("\t\t\t\tstr+=\"<i class='fa fa-times'></i></button></span></div></li>\";\r\n");
      out.write("\t\t\t}\t\t\t \r\n");
      out.write("\t\t})\r\n");
      out.write("\t\tuploadResult.append(str);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//첨부파일 Type 및 Size 제한\r\n");
      out.write("\tfunction checkExtension(fileName, fileSize){\r\n");
      out.write("\t\tlet regex = new RegExp(\"(.*?)\\.(exe|sh|zip|alz)$\");\r\n");
      out.write("\t\tlet maxSize=2097152;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(fileSize>maxSize){\r\n");
      out.write("\t\t\talert(\"파일 크기 초과\");\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(regex.test(fileName)){\r\n");
      out.write("\t\t\talert(\"해당 종류의 파일은 업로드 할 수 없습니다. (exe, sh, zip, alx)\")\r\n");
      out.write("\t\t\treturn false; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//현재 글의 글 번호 가져오기\r\n");
      out.write("\tlet bno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modify.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t//bno를 보내서 해당 게시물의 첨부파일 내역 가져오기\r\n");
      out.write("\t//http://~~/board/getAttachList\r\n");
      out.write("\t$.getJSON(\"getAttachList\", {bno:bno}, function(data){\r\n");
      out.write("\t\tconsole.log(data);\t//json 형태로 데이터 도착\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlet str=\"\";\r\n");
      out.write("\t\t//첨부파일 목록을 보여줄 영역 찾아오기\r\n");
      out.write("\t\tlet uploadResult=$(\".uploadResult ul\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(data).each(function(i,item){\r\n");
      out.write("\t\t\tif(item.fileType){\t//이미지\r\n");
      out.write("\t\t\t\tvar fileCallPath=encodeURIComponent(item.uploadPath+\"\\\\s_\"+item.uuid+\"_\"+item.fileName);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tstr+=\"<li data-path='\"+item.uploadPath+\"' data-uuid='\"+item.uuid+\"'\";\r\n");
      out.write("\t\t\t\tstr+=\" data-filename='\"+item.fileName+\"' data-type='\"+item.fileType+\"'>\";\r\n");
      out.write("\t\t\t\tstr+=\"<div><span><a>\"+item.fileName+\"</span>\";\r\n");
      out.write("\t\t\t\tstr+=\"<button type='button' class='btn btn-danger btn-circle btn-sm' data-file='\"+fileCallPath+\"' data-type='image'>\";\r\n");
      out.write("\t\t\t\tstr+=\"<i class='fa fa-times'></i></button></div>\";\r\n");
      out.write("\t\t\t\tstr+=\"<img src='/display?fileName=\"+fileCallPath+\"'></a></li>\";\r\n");
      out.write("\t\t\t}else{\t//일반 파일\r\n");
      out.write("\t\t\t\tvar fileCallPath=encodeURIComponent(item.uploadPath+\"\\\\\"+item.uuid+\"_\"+item.fileName);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tstr += \"<li data-path='\"+ item.uploadPath +\"' data-uuid='\"+item.uuid+\"'\";\r\n");
      out.write("\t\t\t\tstr += \" data-filename='\"+item.fileName+\"' data-type='\"+item.fileType+\"'>\";\r\n");
      out.write("\t\t\t\tstr += \"<div><span><a>\"+item.fileName+\"</span>\";\r\n");
      out.write("\t\t\t\tstr+=\"<button type='button' class='btn btn-danger btn-circle btn-sm' data-file='\"+fileCallPath+\"' data-type='file'>\";\r\n");
      out.write("\t\t\t\tstr+=\"<i class='fa fa-times'></i></button></div>\";\r\n");
      out.write("\t\t\t\tstr += \"<img src='/resources/img/attach.png'></a></li>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\tuploadResult.html(str);\r\n");
      out.write("\t})//첨부파일 내역 종료\r\n");
      out.write("\t\r\n");
      out.write("\t//첨부파일 처리\r\n");
      out.write("\t$(\".uploadResult\").on(\"click\", \"li\", function(){\r\n");
      out.write("\t\t//이미지 파일은 크게 보여주고, 일판 파일은 다운로드 창 띄우기\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//클릭된 객체 가져오기\r\n");
      out.write("\t\tlet liObj=$(this);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//인코딩\r\n");
      out.write("\t\tvar fileCallPath=encodeURIComponent(liObj.data(\"path\")+\"\\\\\"+liObj.data(\"uuid\")+\"_\"+liObj.data(\"filename\"));\r\n");
      out.write("\t\tif(liObj.data(\"type\")){\r\n");
      out.write("\t\t\tshowImage(fileCallPath.replace(new RegExp(/\\\\/g), \"/\"));\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tlocation.href=\"/download?fileName=\"+fileCallPath;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})//첨부파일 처리 종료\r\n");
      out.write("\t\r\n");
      out.write("\t//확대 사진 닫기\r\n");
      out.write("\t$(\".bigPictureWrapper\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\".bigPicture\").animate({width: '0%', height: '0%'}, 1000);\r\n");
      out.write("\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t$(\".bigPictureWrapper\").hide();\t//bigPictureWrapper 를 숨기는 절차\r\n");
      out.write("\t\t}, 1000);\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t//x를 누르면 서버 폴더에서 삭제하고 목록에서 삭제하기\r\n");
      out.write("\t$(\".uploadResult\").on(\"click\", \"button\", function(){\r\n");
      out.write("\t\t//삭제해야 할 파일 경로\r\n");
      out.write("\t\tlet targetFile=$(this).data(\"file\");\r\n");
      out.write("\t\t//삭제해야 할 파일 타입\r\n");
      out.write("\t\tlet type=$(this).data(\"type\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log(\"targetFile : \"+targetFile);\r\n");
      out.write("\t\tconsole.log(\"type : \"+type);\r\n");
      out.write("\t\tlet targetLi=$(this).closest(\"li\");\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"/deleteFile\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tfileName:targetFile,\r\n");
      out.write("\t\t\t\ttype:type\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\ttargetLi.remove();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t//다음 이벤트 발생 막기\r\n");
      out.write("\t\te.stopPropagation();\r\n");
      out.write("\t})\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\tlet form=$(\"#myForm\");\r\n");
      out.write("\t$(\"button\").click(function(e){\r\n");
      out.write("\t\t//버튼은 모두 submit 형태이기 때문에 submit 속성 중지시키기\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//버튼이 눌러지면 어느 버튼에서 온 것인지 알아내기\r\n");
      out.write("\t\tlet oper=$(this).data(\"oper\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(oper === 'modify') {\r\n");
      out.write("\t\t\t//Modify 버튼을 누르면 수정 폼 보내기\r\n");
      out.write("\t\t\tform=$(\"form[role='form']\");\r\n");
      out.write("\t\t\t//첨부파일 정보를 수집해서 수정 버튼이 눌러지면 다시 보내기\r\n");
      out.write("\t\t\tlet str=\"\";\r\n");
      out.write("\t\t\t$(\".uploadResult ul li\").each(function(i, item){\r\n");
      out.write("\t\t\t\tlet job=$(item);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tstr+=\"<input type='hidden' name='attachList[\"+i+\"].uuid' value='\"+job.data(\"uuid\")+\"'>\";\r\n");
      out.write("\t\t\t\tstr+=\"<input type='hidden' name='attachList[\"+i+\"].uploadPath' value='\"+job.data(\"path\")+\"'>\";\r\n");
      out.write("\t\t\t\tstr+=\"<input type='hidden' name='attachList[\"+i+\"].fileName' value='\"+job.data(\"filename\")+\"'>\";\r\n");
      out.write("\t\t\t\tstr+=\"<input type='hidden' name='attachList[\"+i+\"].fileType' value='\"+job.data(\"type\")+\"'>\";\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\tconsole.log(str);\r\n");
      out.write("\t\t\tform.append(str);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else if(oper === 'remove') {\r\n");
      out.write("\t\t\t//Remove가 눌러지면 myForm 보내기\r\n");
      out.write("\t\t\tform.attr(\"action\", \"remove\");\r\n");
      out.write("\t\t}else if(oper === 'list') {\r\n");
      out.write("\t\t\t//List가 눌러지면 bno는 삭제하고 method=get 방식으로 myForm 보내기\r\n");
      out.write("\t\t\tform.attr(\"action\", \"list\");\r\n");
      out.write("\t\t\tform.attr(\"method\", \"get\");\r\n");
      out.write("\t\t\tform.find(\"input[name='bno']\").remove();\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t})\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write(" </div>\r\n");
      out.write("        <!-- /#page-wrapper -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#wrapper -->\r\n");
      out.write("    <!-- jQuery --> \r\n");
      out.write("    <script src=\"/resources/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- Metis Menu Plugin JavaScript -->\r\n");
      out.write("    <script src=\"/resources/vendor/metisMenu/metisMenu.min.js\"></script>    \r\n");
      out.write("    <!-- Custom Theme JavaScript -->\r\n");
      out.write("    <script src=\"/resources/dist/js/sb-admin-2.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("       ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
